# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobileCenterApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobileCenterApp
  pod 'MobileCenter/Crashes', '~> 0.13.0'
  pod 'MobileCenter/Analytics', '~> 0.13.0'
  pod 'RNMobileCenterShared', '~> 0.10.0'

  

  target 'mobileCenterAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'mobileCenterApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobileCenterApp-tvOS

  target 'mobileCenterApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
